### ISSUE TITLE
Unable to ssh after flashing 16.3 on TG789vac v2

### ISSUE THREAD

**Issue by kurtinaitis** [mswhirl/autoflashgui#11]
Hello, I've done flashing 17.2 and then 16.3 on my TG789vac v2 using these instructions: https://whirlpool.net.au/wiki/hack_technicolor and those firmwares: 

- https://uno.help/attachments/732 ('MST TG789vac v2 17.2.278-0901008.rbi')
- ftp://ftp.iinet.net.au/pub/iinet/firmware/TG789vacV2/VANT-6/vant-6_16.3.8046-ver3.0-CRF767-2721002.rbi

The output does not say anything bad, I can confirm version of the flashed firmware using the browser.
But after flashing and running commands I am unable to connect to device using ssh. It seems, the device is not listening on ports 22 or 6666.
When I try to run some command using browser, It get an error (but the POST request returns 200):
```
IP address: :::::::;/etc/init.d/dropbear restart
Invalid IP address Label within domain name has invalid syntax
```
Is there some problem with this rooting method?

**Comment by kurtinaitis** [comment]
The command execution could maybe check for form validation errors in the returned markup.
But anyway - my problem is already solved.
Thanks a lot for your great job with this script. The forum is also very friendly and helpful.

**Comment by mcohrs** [comment]
> The command execution could maybe check for form validation errors in the returned markup.
> But anyway - my problem is already solved.
> Thanks a lot for your great job with this script. The forum is also very friendly and helpful.

How did you fix it ?
Having the same router and the same issue.
Thx
