### ISSUE TITLE
Proposals of changes/improvements for autoflashgui

### ISSUE THREAD

**Issue by bovirus** [mswhirl/autoflashgui#13]
Proposals of changes/improvements for autoflashgui

- Check Firmware file (define in defaults.ini) availbility.

- Add "Firmware" sub-folder (for firmware files)

- Add a "Browse" control to select firmware file (also keep setting in defaults.ini) 

- Replace "Modem" box selection check box (on the right) with a drop down list selection type.

**Comment by mswhirl** [comment]
Changes made, please check.  If acceptable please close.
