### ISSUE TITLE
[SOLVED] Cannot install

### ISSUE THREAD

**Issue by kotatsuman** [mswhirl/autoflashgui#21]
I am running Linux Mint 19.1, installed `python3.7`, installed `robobrowser` using `pip`, but when I run `python autoflashgui.py` this is what happens:

`Traceback (most recent call last):`
`  File "autoflashgui.py", line 13, in <module>`
`    import tkinter as tk`
`ImportError: No module named tkinter`

That's where I get stuck. I also installed `python-tk` and `python3-tk`, but it did not help.
What should I do? I had a look in a few forums, but got no clue.
Thank you

**Comment by kotatsuman** [comment]
I solved by myself, accidentally, trying this:

`pip install --update pip`

Then `pip` stopped to work, so I had to use `pip3` instead.

`pip3 install setuptools`
`pip3 install wheel`
`pip3 install robobrowser==0.5.3`

"Well", I thought, "if I'm using pip3, I should use python3, then."

`python3 autoflashgui.py`

Oh, wonder! Everything is working like a charm!

**Comment by kevdagoat** [comment]
Simple mistake :)

Next time for your info, you shouldn’t need to specify the robobrowser version

**Comment by mswhirl** [comment]
Thanks for providing feedback on how you solved the problem so that others may benefit!  Regards, Mark.

**Comment by soswow** [comment]
That wasn't enough for me. So I had to do some digging. In case it can help someone on Mac (modern one)
```
brew install python@3.13
brew install python-tk@3.13
python3.13 -m venv ~/venv/autoflashgui 
source ~/venv/autoflashgui/bin/activate
pip install --upgrade pip
pip install robobrowser==0.5.3
python autoflashgui.py
```
now it works for me too
