### ISSUE TITLE
[ENHANCEMENT] add support for 788VN TELMEX 17.2.0360

### ISSUE THREAD

**Issue by FrancYescO** [mswhirl/autoflashgui#26]
Commands needed for the root here:
https://www.ilpuntotecnico.com/forum/index.php/topic,80404.msg249992.html#msg249992

**Comment by mswhirl** [comment]
Hi FrancYescO, I have had a look and it looks like it would require interaction with files on an external USB stick.  While I am happy to put a line in defaults.ini to enable this method, I can't control the USB stick path (they seem to change path on my modem occasionally depending on the stick used, so this is just asking for trouble when hard coding a path).  Please have a look at https://github.com/kevdagoat/hack-technicolor/issues/68 as the approach may be able to be ported over to your modem once it's developed, but you would need to test it.  I am closing this issue now but if you wish to suggest a suitable defaults.ini line I am happy to add it later, or test a future method for your modem.  Regards, Mark.

**Comment by FrancYescO** [comment]
Ignore the USB part, all commands can be putted in the DNS like we do in all other modems

Just take all commands from the sh script
