### ISSUE TITLE
ValueError preventing program launch

### ISSUE THREAD

**Issue by BeecoLair** [mswhirl/autoflashgui#27]
Traceback (most recent call last):
  File "autoflashgui.py", line 231, in <module>
    print(sys.argv, sys.path, os.getcwd())
  File "autoflashgui.py", line 36, in getDefaults
    config[configKey] = record
ValueError: not enough values to unpack (expected 4, got 3)
[13508] Failed to execute script autoflashgui

This is stopping autoflashgui from starting in cmd.

**Comment by Schuby** [comment]
The last two lines of defaults.ini are missing an argument, vMethod, which autoflashgui.py is looking for.

Replacing the last two lines of defaults.ini to look like the following should fix it.
`variant=Generic (Advanced DDNS),AdvancedDDNS,dyndns.it,sed -i 's#/root:.*$#/root:/bin/ash#' /etc/passwd;echo root:root | chpasswd;sed -i.save 's/#//' /etc/inittab;uci add dropbear dropbear;uci rename dropbear.@dropbear[-1]=afg;uci set dropbear.afg.enable='1';uci set dropbear.afg.Interface='lan';uci set dropbear.afg.Port='22';uci set dropbear.afg.IdleTimeout='600';uci set dropbear.afg.PasswordAuth='on';uci set dropbear.afg.RootPasswordAuth='on';uci set dropbear.afg.RootLogin='1';uci commit dropbear;/etc/init.d/dropbear enable;/etc/init.d/dropbear restart;uci commit
variant=Generic (Ping),Ping,dyndns.com,sed -i 's#/root:.*$#/root:/bin/ash#' /etc/passwd;echo root:root | chpasswd;sed -i.save 's/#//' /etc/inittab;uci add dropbear dropbear;uci rename dropbear.@dropbear[-1]=afg;uci set dropbear.afg.enable='1';uci set dropbear.afg.Interface='lan';uci set dropbear.afg.Port='22';uci set dropbear.afg.IdleTimeout='600';uci set dropbear.afg.PasswordAuth='on';uci set dropbear.afg.RootPasswordAuth='on';uci set dropbear.afg.RootLogin='1';uci commit dropbear;/etc/init.d/dropbear enable;/etc/init.d/dropbear restart;uci commit
`

**Comment by kevdagoat** [comment]
Please redownload the defaults.ini file and then report back

**Comment by BeecoLair** [comment]
Redownload. It loaded and it now starts up the GUI.
Cheers!

**Comment by kevdagoat** [comment]
Very welcome. There was recently an update to the defaults, hence why I got you to redownload 😄

**Comment by Schuby** [comment]
Hmm, redownloading didn't change anything for me. I still needed to make those changes I listed above to get it the GUI to load up. I'm on Windows 10 with Python 3.8.0.

**Comment by kevdagoat** [comment]
Try re-cloning the repository and start from there

**Comment by mswhirl** [comment]
I have fixed this problem.  Thanks for bringing it to my attention!  Regards, Mark.
