### ISSUE TITLE
Text Boxes Too Narrow

### ISSUE THREAD

**Issue by flywire** [mswhirl/autoflashgui#5]
Seems text box width setting changed:

![image](https://user-images.githubusercontent.com/11288701/50382352-630a1180-06f1-11e9-8da2-52528163356e.png)

**Comment by mswhirl** [comment]
I suspect this is to do with font scaling on different machines.  I will add in a bit more 'play' for the text boxes tomorrow.

**Comment by flywire** [comment]
Image from a Toshiba laptop running Win7, 1600x900 resolution. Looks like a conflict with 125% text and other items size setting.

**Comment by mswhirl** [comment]
Flywire, I have increased the spacing slightly.  If necessary you can also edit the .py and change the multiplier from 1 to 2 which will give heaps of spacing.  Please re-open this if it's still not working correctly!  Cheers, Mark.
