### ISSUE TITLE
Proposal - Move build.cmd/clean cmd file to tools sub-folder

### ISSUE THREAD

**Issue by bovirus** [mswhirl/autoflashgui#7]
Hello.

I have a prossoal about a moving of some files of main folder.

**_build.cmd_** and **_clean.cmd_** can be moved under tools sub-older (of course you have to modify bild.cmd/clean.cmd to reflect the new location) to have all commands unddr tools sub-folder.

What do you think about it?

I pushed this morining the PR.

I added also some checks about file/folfers exist

**Comment by mswhirl** [comment]
Done.  Thank you.
